### ISSUE TITLE
US-RSE 24 submission checklist

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-usrse24-submission#1]
### Notebook file in any of the following formats:

~~- [ ] .qmd (jupyter kernel or knitr engine)~~
- [x] .ipynb (jupyter kernel)
~~- [ ] .Rmd (jupyter kernel or knitr engine)~~

###  README.md which should contain:

- [x] Title
- [x] Abstract
- [x] Any necessary instructions for use:
- [x] For notebooks with interactivity: a walk-through of typical usage, intended for reviewers to reproduce. *See the “Reproducibility Considerations” page.

###  Citation file: CITATION.cff format.

- [x] See https://citation-file-format.github.io/ for more information and a tool to create a CITATION.cff file online

### LICENSE: 

- [x] include a software license with at least enough permissions for the US-RSE organization to publish in the US-RSE’24 conference proceedings.

###  Environment file(s) in any of the following formats:

- [x] [environment.yml](https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html#conda-environment-with-environment-yml) (Python/Conda and R/Conda)[RECOMMENDED]
- [x] [requirements.txt](https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html#python-environment-with-a-requirements-txt) (Python/pip)
~~- [ ] [install.R and optionally runtime.txt](https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html#specifying-an-r-environment-with-a-runtime-txt-file) (R/MRAN)~~
~~- [ ] [DESCRIPTION and optionally runtime.txt](https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html#specifying-an-r-environment-by-having-a-description-file) (R/MRAN)~~

###  Optional: Additional packaging file to set up your own local library

~~- [ ] pyproject.toml / [setup.py](https://mybinder.readthedocs.io/en/latest/examples/sample_repos.html#python-package-with-setup-py) (Python)~~
